config/routes.rb
Ritly::Application.routes.draw do
  root 'rits#index'

  resources :rits do
      member do
        get 'preview'
      end
    end

end

app/models/rit.rb
class Rit < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rits_controller.rb
class RitsController < ApplicationController
	def index
		@ritly = Rit.all
	end

	def new
		@ritly = Rit.new
	end

	def create
		@ritly = Rit.new(safe_rit_param)
		@ritly.hashcode = rand(100000)

		@ritly.save
	end

	def show
		@ritly = Rit.find(params[:id])
	end

	def edit
		@ritly = Rit.find(params[:id])
	end

	def destroy
		@ritly = Rit.find(params[:id])
		@ritly.destroy

		redirect_to root_path
	end	

	def preview
		@ritly = Rit.find(params[:id])
	end

	private

	def safe_rit_param
		params.require(:rit).permit(:url)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ritlies_helper.rb
module RitliesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ritly</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1><a href="<%= root_path %>">Ritly</a></h1>
<br>

<%= yield %>

</body>
</html>

app/views/rits/_form.html.erb
<h1><%= @ritly.hashcode %> is your code for <%= @ritly.url %></h1>

<p>You can direct to this Ritly URL: <a href="<%= @ritly.url %>"><%= @ritly.url %></a></p>
<br>
<p>The Ritly URL will redirect them to: <a href="<%= preview_rit_path %>" target="_blank"><%= @ritly.hashcode %></a></p>

app/views/rits/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @ritly %> |
<%= link_to 'Back', root_path %>

app/views/rits/index.html.erb
<h3>Welcome to ritly</h3>

<a href="<%= new_rit_path %>">Click here to create a new short link</a>

app/views/rits/new.html.erb
<h3>New Ritly URL</h3>
<br>

<p>Enter URL to shorten</p>
<%= form_for @ritly do |f| %>
	<%= f.text_field :url  %>
	<br>
	<%= f.submit "Create Short URL" %>
<% end %>

app/views/rits/preview.html.erb
<a href="<%= @ritly.url %>"><%= @ritly.url %></a>

app/views/rits/show.html.erb
<%= render 'form' %>

<%= link_to 'Destroy', rit_path(@ritly), :method => :delete %> | 
<%= link_to 'Edit', edit_rit_path(@ritly) %> |
<%= link_to 'Back', root_path %>